# Generated by Django 2.2.5 on 2019-09-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question.Question'),
        ),
        migrations.AlterField(
            model_name='answeredquestion',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='question.Answer'),
        ),
        migrations.AlterField(
            model_name='answeredquestion',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='user_profile.UserProfile'),
        ),
    ]
