{% raw %}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
    stage: {{ .Values.stage }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      stage: {{ .Values.stage }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
        stage: {{ .Values.stage }}
    spec:
      containers:
        - name: database-container
          image: 'postgres:10.11'
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password

            - name: POSTGRES_DB
              value: postgresdb

          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-disk
              # see: https://stackoverflow.com/questions/51168558/how-to-mount-a-postgresql-volume-using-aws-ebs-in-kubernete/51174380
              subPath: postgres
          ports:
            - name: postgresql-5432
              containerPort: 5432
      volumes:
        - name: database-disk
          persistentVolumeClaim:
            claimName: database-disk
{% endraw %}
