{% raw %}
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  labels:
    stage: {{ .Values.stage }}
type: Opaque
data:
  user: {{ "postgresadmin" | b64enc | quote }}
  password: {{ "admin123" | b64enc | quote }}
{% endraw %}
