apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
    stage: {{ .Values.stage }}
spec:
  replicas: {{ .Values.django.replicas }}
  selector:
    matchLabels:
      app: server
      stage: {{ .Values.stage }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: {{ .Values.stage }}
        app: server
    spec:
      containers:
        - name: server
          image: {{ .Values.django.image }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.django.livenessPath }}
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.host }}
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: {{ .Values.django.readinessPath }}
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.host }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
          {{- include "doppelganger.djangoStandardEnv" . | nindent 10 }}
      imagePullSecrets:
        - name: gcr-json-key
