---
# Global settings
host: {{ cookiecutter.local_domain_name }}
stage: dev
sentryDsn: {{ cookiecutter.sentry_dsn }}

# Can set this to relevant value based on k8s cloud provider's storage class
# i.e. do-block-storage for digital ocean
# storageClassName: do-block-storage

client:
  image:  '{{ cookiecutter.docker_registry_path }}/client'
  replicas: 1
  readinessPath: /
  livenessPath: /
  apiServerUrl: http://{{ cookiecutter.local_domain_name }}/api
  apiGraphqlServerUrl: http://{{ cookiecutter.local_domain_name }}/api/graphql
  apiCsrftokenUrl: http://{{ cookiecutter.local_domain_name }}/api/admin

django:
  image: '{{ cookiecutter.docker_registry_path }}/server'
  replicas: 1
  readinessPath: /api/admin
  livenessPath: /api/admin

ingress:
  enabled: true

redis:
  password: foobar1234
  master:
    persistence:
      size: 1Gi
  slave:
    persistence:
      size: 1Gi
