kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-disk
  namespace: doppelganger
  labels:
    app: database
    stage: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
