{% raw %}
apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      containers:
        - name: django
          image: {{ include "doppelganger.django.image" . }}
          command:
            - /bin/bash
            - -c
            - |
              python manage.py migrate &&
              python manage.py graphql_schema
          {{- include "doppelganger.djangoStandardEnv" . | nindent 10 }}
      restartPolicy: Never
      imagePullSecrets:
        - name: gcr-json-key
  backoffLimit: 5
{% endraw %}
