{% raw %}
kind: Service
apiVersion: v1
metadata:
  name: server-service
  labels:
    stage: {{ .Values.stage }}
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
{% endraw %}
