kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-disk
  labels:
    app: database
    stage: {{ .Values.stage }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.storageClassName | default "standard" }}
