kind: Service
apiVersion: v1
metadata:
  name: database-service
  labels:
    stage: {{ .Values.stage }}
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
