version: '3'

services:

  client:
    build:
      # Context is this directory instead of ./client because Dockerfile
      # needs to copy schema.graphql file which is located in ./server
      context: .
      dockerfile: ./client/Dockerfile
    command: npm run start
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./server/schema:/app/schema # Need to keep schema up to date based off of server
      - /app/build
      - /app/public
    tty: true
    stdin_open: true
    ports:
      - 8080:8080

  server:
    build:
      context: ./server
    command:
      - /bin/bash
      - -c
      - |
        ./wait-for.sh database:5432
        python manage.py migrate
        python manage.py graphql_schema
        python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
      - redis
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
    tty: true
    stdin_open: true
    ports:
      - 8000:8000

  redis:
    restart: always
    image: 'redis:5.0.7'
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  celery:
    build:
      context: ./server
    command: celery -A doppelganger worker -l info
    volumes:
      - ./server:/app
    depends_on:
      - database
      - redis
    env_file:
      - ./server/.env
    environment:
      - SENTRY_DSN=${SENTRY_DSN}

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
        - redis

  database:
    image: 'postgres:10.11'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: admin123
    volumes:
    - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
  redisdata: ~
