---
# Global settings
host: doppelganger.local
stage: dev
sentryDsn: https://19d74ebe7b174d399ebcb96320129b6b@sentry.io/1827306

# Can set this to relevant value based on k8s cloud provider's storage class
# i.e. do-block-storage for digital ocean
# storageClassName: do-block-storage

client:
  image:  'gcr.io/graphql-django-apollo-starter/client'
  replicas: 1
  readinessPath: /
  livenessPath: /
  apiServerUrl: http://doppelganger.local/api
  apiGraphqlServerUrl: http://doppelganger.local/api/graphql
  apiCsrftokenUrl: http://doppelganger.local/api/admin

django:
  image: 'gcr.io/graphql-django-apollo-starter/server'
  replicas: 1
  readinessPath: /api/admin
  livenessPath: /api/admin

ingress:
  enabled: true

redis:
  password: foobar1234
