{% raw %}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-ingress
  namespace: {{.Release.Namespace}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: client-service
              servicePort: 80
          - path: /api
            backend:
              serviceName: server-service
              servicePort: 8000
{% endraw %}
