---
# THIS IS AN EXAMPLE OF A STAGING VALUES.YAML AND YOU SHOULD CHANGE VALUES
# TO MATCH YOUR ENVIRONMENT AND DESIRED CONFIGURATION!!!
#
# Global settings
#
# TODO: FIX THIS COOKIECUTTER REFERENCE
host: review.{{ cookiecutter.domain_name }}
stage: review
sentryDsn: {{ cookiecutter.sentry_dsn }}

# Can set this to relevant value based on k8s cloud provider's storage class
# i.e. do-block-storage for digital ocean
storageClassName: do-block-storage

client:
  image:  '{{ cookiecutter.docker_registry_path }}/client'
  replicas: 1
  readinessPath: /
  livenessPath: /
  apiServerUrl: http://review.{{ cookiecutter.domain_name }}/api
  apiGraphqlServerUrl: http://review.{{ cookiecutter.domain_name }}/api/graphql
  apiCsrftokenUrl: http://review.{{ cookiecutter.domain_name }}/api/admin

django:
  image: '{{ cookiecutter.docker_registry_path }}/server'
  replicas: 1
  readinessPath: /api/admin
  livenessPath: /api/admin

ingress:
  enabled: true

redis:
  password: foobar1234
