---
# THIS IS AN EXAMPLE OF A STAGING VALUES.YAML AND YOU SHOULD CHANGE VALUES
# TO MATCH YOUR ENVIRONMENT AND DESIRED CONFIGURATION!!!
#
# Global settings
host: staging.graphql-django-apollo-starter.club
stage: staging
sentryDsn: https://19d74ebe7b174d399ebcb96320129b6b@sentry.io/1827306

# Can set this to relevant value based on k8s cloud provider's storage class
# i.e. do-block-storage for digital ocean
storageClassName: do-block-storage

client:
  image:  'gcr.io/graphql-django-apollo-starter/client'
  replicas: 1
  readinessPath: /
  livenessPath: /
  apiServerUrl: http://staging.graphql-django-apollo-starter.club/api
  apiGraphqlServerUrl: http://staging.graphql-django-apollo-starter.club/api/graphql
  apiCsrftokenUrl: http://staging.graphql-django-apollo-starter.club/api/admin

django:
  image: 'gcr.io/graphql-django-apollo-starter/server'
  replicas: 1
  readinessPath: /api/admin
  livenessPath: /api/admin

ingress:
  enabled: true

redis:
  password: foobar1234
