name: 'Publish Docker'
on: ['push']

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v1'

    - name: Publish images to Registry
      env:
        GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
      run: |
            echo $GCLOUD_KEY | docker login -u _json_key --password-stdin https://gcr.io
            make build push
