name: 'Publish Docker'
on: ['push']

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v1'

    - name: Login to gcloud registry
      id: gcloud
      uses: elgohr/gcloud-login-action@master
      with:
        account_key: ${{ secrets.GCLOUD_KEY }}
    - name: Publish server to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: graphql-django-apollo-starter/server
        username: ${{ steps.gcloud.outputs.username }}
        password: ${{ steps.gcloud.outputs.password }}
        registry: gcr.io
        context: ./server/
    - name: Publish client to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: graphql-django-apollo-starter/client
        username: ${{ steps.gcloud.outputs.username }}
        password: ${{ steps.gcloud.outputs.password }}
        registry: gcr.io
        context: ./
        dockerfile: ./client/Dockerfile
