name: 'Deploy'
on: ['deployment']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate cookie cut project
      run: cookiecutter . --no-input

    - name: Helm dependency updates
      working-directory: ./graphql_django_apollo_starter
      run: |
        curl -LO https://get.helm.sh/helm-v3.0.3-linux-amd64.tar.gz \
        && tar -zxvf helm-v3.0.3-linux-amd64.tar.gz \
        && ./linux-amd64/helm repo add stable https://kubernetes-charts.storage.googleapis.com \
        && ./linux-amd64/helm repo update \
        && ./linux-amd64/helm dependency update ./kubernetes/doppelganger

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        helm: helm3
        namespace: doppelganger
        chart: graphql_django_apollo_starter/kubernetes/doppelganger
        token: ${{ github.token }}
        secrets: ${{ toJSON(secrets) }}
        version: ${{ github.sha }}
        values: |
          gitSha: ${{ github.sha }}
      env:
        KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
