name: 'Deploy'
on: ['deployment']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'

    - name: 'Setup Helm'
      uses: azure/setup-helm@v1
      with:
        version: '3.0.1'
      id: install

    - name: 'Helm dependency updates'
      run: helm repo update && helm dependency update ./kubernetes/doppelganger

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        helm: helm3
        namespace: doppelganger
        chart: 'kubernetes/doppelganger'
        token: '${{ github.token }}'
        secrets: '${{ toJSON(secrets) }}'
        version: '${{ github.sha }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
